"""add awareness_tips table

Revision ID: b9d042068fa2
Revises: 
Create Date: 2025-11-12 16:37:33.210683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b9d042068fa2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('awareness_topic')
    op.drop_table('awareness')
    op.drop_table('training')
    op.drop_table('quiz_attempt')
    op.drop_table('staff')
    op.drop_table('quiz')
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('user_id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('email', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('password_hash', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('role', mysql.ENUM('ADMIN', 'STAFF'), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('quiz',
    sa.Column('quiz_id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('correct_answer', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('optiona', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('optionb', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('optionc', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('optiond', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('question', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('topic_id', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['awareness_topic.topic_id'], name='FKe21cg0y8qd875nmj0uy3bl82l'),
    sa.PrimaryKeyConstraint('quiz_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('staff',
    sa.Column('user_id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('department', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('password_hash', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('role', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('quiz_attempt',
    sa.Column('attempt_id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('attempt_date', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('is_correct', mysql.BIT(length=1), nullable=False),
    sa.Column('selected_answer', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('quiz_id', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('user_id', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['quiz_id'], ['quiz.quiz_id'], name=op.f('FK8l6wmgul0rgeha0lp6abrp5fa')),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], name=op.f('FK9du1u7kyyo9vd7wp4m3exo9x7')),
    sa.PrimaryKeyConstraint('attempt_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('training',
    sa.Column('training_id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('date', sa.DATE(), nullable=True),
    sa.Column('description', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('topic', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('training_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('awareness',
    sa.Column('awareness_id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('score', mysql.DOUBLE(asdecimal=True), nullable=False),
    sa.Column('staff_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('topic', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('awareness_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('awareness_topic',
    sa.Column('topic_id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('content_link', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('description', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('title', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.PrimaryKeyConstraint('topic_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
